### PR TITLE
WinWrap Basic dialect

### LINKED ISSUE #57: AndAlso, OrElse, IsNot
I want to add highlighting for keywords `AndAlso`, `OrElse` and `IsNot`.
These keywords are not supported in VBA, but I want to use this extension for other VB language.
Is it OK?

### PR DESCRIPTION
**Pull request by stepanhakobyan**
close #57

### CODE REVIEW

**Comment by h8nor** [comment]
> This language element is not VBA compatible
* https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_decimal_datatype.htm
* https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_huge_datatype.htm
* https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_sbyte_datatype.htm
* https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_uhuge_datatype.htm
* https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_uinteger_datatype.htm
* https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_ulong_datatype.htm
> and
* https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_isnot__oper.htm
* https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_return__instr.htm
* https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_portint_datatype.htm
> and some
* https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_operators__oper.htm

**Comment by stepanhakobyan** [comment]
> > This language element is not VBA compatible
> 
>     * https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_decimal_datatype.htm
> 
>     * https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_huge_datatype.htm
> 
>     * https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_sbyte_datatype.htm
> 
>     * https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_uhuge_datatype.htm
> 
>     * https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_uinteger_datatype.htm
> 
>     * https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_ulong_datatype.htm
> 
> 
> > and
> 
>     * https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_isnot__oper.htm
> 
>     * https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_return__instr.htm
> 
>     * https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_portint_datatype.htm
> 
> 
> > and some
> 
>     * https://www.winwrap.com/web2/basic/#!/ref/WWB-doc_operators__oper.htm

@h8nor I don't know what else to say. 
I already said that WWB is a superset of VBA, and that is the reason for making a separate language (in this repository), and not including this keywords and types in VBA language.

**Comment by h8nor** [comment]
I refer what is written in the WWB documentation.

**Review by serkonda7 — APPROVED** [review]
I added a commit with minor changes and a test to make sure vba is not affected by wwb.

**Comment by serkonda7** [comment]
@stepanhakobyan great work, thank you a lot 💯

**Comment by serkonda7** [comment]
@stepanhakobyan I just saw that you used `.wwd` as file extension, whereas [this source](https://www.wikiwand.com/en/WinWrap_Basic) says otherwise:
> The default file extension for programmes written in this language is .wwb

**Comment by stepanhakobyan** [comment]
@serkonda7  here is the screenshot of Save As dialog. "wwd" is the default there.
Actually I didn't wanted to put any default extension in the package.json, but couldn't build that way.
image

**Pull request merged**
